-- bootstrap lazy.nvim, LazyVim and your plugins
-- vim.uv = vim.uv or vim.loop
--
-- local M = {}
--
-- ---@param opts? LazyVimConfig
-- function M.setup(opts)
--   require("config").setup(opts)
-- end
--
-- return M
require("config.lazy")
