require("options")
require("keymappings")

require("plugins")
require("colorscheme")
require("gitsigns")
require("cmp")
require("project")
require("bufferline")
require("floatterm")
require("telescope")
require("treesitter")
require("which-key")
require("nvimtree")
require("utils")
require("null-ls")
require("lsp")
