#!/bin/sh
log "zsh-exports: starting exports"
export TERM=xterm-256color
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

#echo "setting node modules variable"
APPS_HOME="/home/amr/Documents/Apps"
NODE_MODULES="/home/amr/Documents/Apps/node_modules"
MONGO_HOME="/home/amr/Documents/Apps/mongodb"
WORK_DIR="/home/amr/Documents/dotfiles"
ANDROID_SDK_ROOT=/home/amr/Documents/Apps/android-sdk-tools/

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
log "zsh-exports: adding fzf"


#echo "setting gradle OPTS"
# This causes grails to fail
export GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.daemon=true"
# User specific environment and startup programs
export JAVA_OPTS="$JAVA_OPTS -Xmx2G -Xms1500M"
#export ANDROID_HOME=/home/amr/Apps/android-sdk-tools/

#echo "initializing sdkman"
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/amr/.sdkman"
source $SDKMAN_DIR/bin/sdkman-init.sh

zsh_add_file "zsh-nvm"

# log "zsh-exports: adding virtualenv"
# ####### PYTHON VIRTUALENV ###############
export WORKON_HOME=$HOME/.local/share/virtualenv/virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_HOOK_DIR=$WORKON_HOME/hooks
[[ -f /usr/local/bin/virtualenv ]] && export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
[[ -f ~/.local/bin/virtualenv ]] && export VIRTUALENVWRAPPER_VIRTUALENV=~/.local/bin/virtualenv
[[ -f ~/.local/bin/virtualenvwrapper.sh ]] && source ~/.local/bin/virtualenvwrapper.sh 

export DBX_ACCESS_TOKEN=xxx

[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)

# $DEBUG && echo "zsh-exports: adding gopath"
# export GOPATH=/home/amr/.local/share/go

#echo "adding path folders"
# ####### Configure PATH ###############
#  - These are line by line so that you can kill one without affecting the others.
#  - Lowest priority first, highest priority last.
PATH="$HOME/.local/bin":$PATH
PATH="$MONGO_HOME/bin:$PATH" # MongoDB home
PATH=$APPS_HOME/tinkerpop/bin:$PATH
PATH=$WORK_DIR/bin:$PATH
PATH=$NODE_MODULES/bin:$PATH # node modules bin
PATH=$GOPATH/bin:$PATH # go
export PATH=$ANDROID_SDK_ROOT/tools/bin/:$ANDROID_SDK_ROOT/emulator/:$ANDROID_SDK_ROOT/tools/bin/:$PATH
