#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

#echo "setting node modules variable"
APPS_HOME="/home/amr/Documents/Apps"
NODE_MODULES="~/Documents/Apps/node_modules"
MONGO_HOME="~/Documents/Apps/mongodb"
WORK_DIR="~/Documents/dotfiles"
ANDROID_SDK_ROOT=/home/amr/Documents/Apps/android-sdk-tools/

#echo "setting gradle OPTS"
# This causes grails to fail
export GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.daemon=true"
# User specific environment and startup programs
export JAVA_OPTS="$JAVA_OPTS -Xmx2G -Xms1500M"
#export ANDROID_HOME=/home/amr/Apps/android-sdk-tools/

#echo "initializing sdkman"
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/amr/.sdkman"

# ####### PYTHON VIRTUALENV ###############
export WORKON_HOME=$HOME/.local/share/virtualenv/virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
[[ -f /usr/local/bin/virtualenv ]] && export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
[[ -f ~/.local/bin/virtualenv ]] && export VIRTUALENVWRAPPER_VIRTUALENV=~/.local/bin/virtualenv
export VIRTUALENVWRAPPER_HOOK_DIR=$WORKON_HOME/hooks
export DBX_ACCESS_TOKEN=xxx

#echo "adding path folders"
# ####### Configure PATH ###############
#  - These are line by line so that you can kill one without affecting the others.
#  - Lowest priority first, highest priority last.
PATH="$HOME/.local/bin":$PATH
PATH="$MONGO_HOME/bin:$PATH" # MongoDB home
PATH=$APPS_HOME/tinkerpop/bin:$PATH
PATH=$WORK_DIR/bin:$PATH
PATH=$NODE_MODULES/bin:$PATH # node modules bin
export PATH=$ANDROID_SDK_ROOT/tools/bin/:$ANDROID_SDK_ROOT/emulator/:$ANDROID_SDK_ROOT/tools/bin/:$PATH
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
