#!/bin/bash

#GO TO LOCATIONS CIPAL
alias et="cd ~/dev/cipal/etend_ws/etendering"
alias etw="cd ~/dev/cipal/etend_ws/etendering/etendering-web/"
alias etdb="cd ~/dev/cipal/etend_ws/etendering/etendering-db/"

# CIPROCURE
alias mysql_test="mysql -u etendering -pgvb3lg13 etendering_test"
alias mysql_speed="/home/amr/dev/scripts/mysql_speedup.sh"
alias mysql_reset="mvn clean install -Pclean-db-test -f $ET_FOLDER/etendering-db/ && mysql -u root -proot etendering_test < $DUMPS_FOLDER/latest.sql && mvn clean install -f $ET_FOLDER/etendering-db/"

DUMPS_FOLDER="/home/amr/dev/cipal/etend_ws/sql/dumps"
ET_FOLDER="/home/amr/dev/cipal/etend_ws/etendering"

pick_db_bkp() {
    TODAY=`date +%Y-%m-%d`
    #TODAY="2016-06-28"
    BKP_FOLDER="/var/backups/mysql/daily/etendering_genk"

    rm -f $DUMPS_FOLDER/*
    scp ci-test:$BKP_FOLDER/*$TODAY* $DUMPS_FOLDER
    gunzip $DUMPS_FOLDER/*.gz
    ln -s $DUMPS_FOLDER/*.sql $DUMPS_FOLDER/latest.sql

    mysql_reset
}

# NOt used 
g_hotfix_start() {
    if [! $# -neq 2 ]; then
        g_hotfix_syntax
    fi
    echo "git checkout release/$1"
    echo "git pull"
    echo "git checkout -b release/$1 hotfix/$1/$2"
}

# NOt used 
g_hotfix_finish() {
    if [! $# -neq 2 ]; then
        g_hotfix_syntax
    fi
    echo "git checkout release/$1"
    echo "git pull"
    echo "git checkout hotfix/$1/$2"
    echo "git rebase -i release/$1"
    echo "git push -f"
    echo "git checkout release/$1"
    echo "git merge hotfix/$1/$2"
    echo "git branch -D hotfix/$1/$2"
    echo "git push origin :hotfix/$1/$2"
}

# NOt used 
g_hotfix_syntax () {
    echo -e "  - The proper Syntax is:"
    echo -e "\t#: g_hotfix_[start|finish] release issue"
    echo -e "  - where:"
    echo -e "\t-- release: is the release candidate number i.e. 1608.02"
    echo -e "\t-- issue: is the issue identifying the fix i.e. ET-3880"
}

alias open_et="open_idea ~/dev/cipal/etend_ws/etendering"
alias open_sts_et="open_sts ~/dev/cipal/etend_ws/etendering"

gfo() {
    git checkout "feature/ET-$1"
}

grd() {
    CURRENT_VERSION=`git rev-parse --abbrev-ref HEAD`
    git checkout develop && git pull && git checkout $CURRENT_VERSION
}

#mysql_speed
