#!/bin/bash
DEV_FOLDER="/home/amr/Projects"
MANNING_FOLDER="$DEV_FOLDER/manning/"

alias lv="cd $PROJECTS/manning/livevideo/ivc/"
alias lb="cd $PROJECTS/manning/livebook/vBook/"
alias ivc="cd $PROJECTS/manning/livevideo/ivc/"
alias ivcbuild="ivc && sdk use gradle 5.6.4 && gradle clean build -x test -x integrationTest"
alias ivcqdeploy="ivcbuild && eb deploy livevideo-qa "
alias lvui="cd $PROJECTS/manning/livevideo/ivc-ui/"
alias lbui="cd $PROJECTS/manning/livebook/livebook-ui/"
alias m="cd $PROJECTS/manning/"
alias mk="cd $PROJECTS/manning/e-commerce/Marketplace"
alias mws="cd $PROJECTS/manning/e-commerce/MarketplaceWS"
alias ma="cd $PROJECTS/manning/e-commerce/MarketplaceAdmin"
alias cas="cd $PROJECTS/manning/otherProjects/cas-override/cas-server"
alias vbuild="sdk use gradle 5.6.4 && lb && gradle clean build -x test -x integrationTest"
alias vqdeploy="vbuild && eb deploy livebook-qa"
alias aws-ecr-login="aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 441712016571.dkr.ecr.us-west-2.amazonaws.com"
alias myuserid="psql -Uroot marketplace -c \"select id from users where username = 'dquijote22@gmail.com'\""
alias s3-ls=s3_ls_summary
OPENSEARCH_COMPOSER_FILE="$MANNING_FOLDER/otherProjects/smart-search-neptune/manning-smart-search-microservice/opensearch-docker-compose.yaml"
alias dcomp-opensearch="docker-compose -f $OPENSEARCH_COMPOSER_FILE"

s3_ls_summary() {
	aws s3 ls --summarize --human-readable --recursive s3://$1
}

pull_m() {
	CWD=$(pwd)
	echo "***************************************"
	echo "*        PULLING MARKETPLACEWS        *"
	echo "***************************************"
	mws
	pull_n_back

	echo "***************************************"
	echo "*         PULLING MARKETPLACE         *"
	echo "***************************************"
	mk
	pull_n_back

	echo "***************************************"
	echo "*     PULLING MARKETPLACEADMIN        *"
	echo "***************************************"
	ma
	pull_n_back

	cd $CWD
}

pull_n_back() {
	CURRENT_VERSION=$(git rev-parse --abbrev-ref HEAD)
	git stash
	gco master && gl
	gco $CURRENT_VERSION
	git stash pop
}

if [ -f ~/Documents/dotfiles/bash/private-manning-aliases ]; then
	source ~/Documents/dotfiles/bash/private-manning-aliases
fi
