#!/bin/bash

DOTFILES=$HOME/dotfiles

# Safety
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
set -o noclobber

# Listing, directories, and motion
alias ..='cd ..'
alias ...='cd ..;cd ..'
alias grep='grep --color=auto'
alias ll="ls -lrtF --color -h --group-directories-first"
alias la="ls -alrtF --color -h --group-directories-first"
alias lA="ls -A"
alias l="ls -CF"
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias m='less'
alias md='mkdir'
#alias du='du -ch --max-depth=1'
alias du='du -ch'
alias treeacl='tree -A -C -L 2'
alias gnome-open=xdg-open

alias aptu="sudo apt update && sudo apt dist-upgrade -y"
alias sb="source ~/.bashrc"
alias myip="curl http://ipecho.net/plain; echo"

alias go-dev="cd /home/amr/dev"
alias a2d="python3 /home/amr/dev/scripts/a2dp.py"

alias vimclean="rm -rf /home/amr/.vimbackup/*"

# vim wiki
wikii() {
    gvim -c ":VimwikiIndex"
}

# Git
alias gst='git status -s'
alias gl='git pull -r'
alias gp='git push'
alias gd='git diff | vim'
alias gau='git add --update'
alias gc='git commit -v -m'
alias gca='git commit -v -a -m'
alias gb='git branch'
alias gba='git branch -a'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcot='git checkout -t'
alias gcotb='git checkout --track -b'
alias glog='git log'
alias glogp='git log --pretty=format:"%h %s" --graph'
alias grp='git remote update -p'
alias grv='git remote -v'

# Git flow
alias gfs="git flow feature start $1"
alias gfp="git flow feature publish $1"
alias gff="git flow feature finish $1"

# TOMCAT
alias t7w="cd /var/lib/tomcat7$1"
alias t7l="sudo tail -f /var/log/tomcat7/catalina.out"
alias t8w="cd /var/lib/tomcat8$1"
alias t8l="sudo tail -f /var/log/tomcat8/catalina.out"
alias t8s="sudo service tomcat8 $1"

open_idea() {
    idea $1 &> /dev/null &
}

open_sts() {
    sts $1 &> /dev/null &
}

bookmark_pwd() {
    path=`pwd`
    path=${path//\//\\/}
    sed -e "/${path}/d" ${DOTFILES}/bash/aliases &>/dev/null
    if [ $? -eq 0 ]; then
        echo "alias $1='cd `pwd`'" >> $DOTFILES/bash/aliases
    else
        echo "Bookmark already exists"
    fi

    source $HOME/.bashrc
}

delete_bookmark_pwd() {
    pattern=$1
    unalias $1
    sed -e "/${pattern}/d" ${DOTFILES}/bash/aliases &>/dev/null

    source $HOME/.bashrc
}

if [ -f $DOTFILES/bash/aliases-cipal ]; 
then
    source $DOTFILES/bash/aliases-cipal
fi

if [ -f $DOTFILES/bash/aliases-manning ]; 
then
    source $DOTFILES/bash/aliases-manning
fi
alias vb3='cd /home/amr/dev/python/django/vatbook'
alias vtmp='cd /home/amr/Documents/Manning/data/db_backups/tmp'
alias mdbackups='cd /home/amr/Documents/Manning/data/db_backups'

SAT_HOME='/home/amr/dev/python/django/sat8485'
alias sat="cd $SAT_HOME"
alias run-sat="$SAT_HOME/manage.py runserver --settings=sat8485.settings.develop"
alias sat_reset_db='rm -f /home/amr/Dropbox/Aplicaciones/sat/db.sqlite3'
