#!/bin/bash

# Safety
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
set -o noclobber

# Listing, directories, and motion
alias ..='cd ..'
alias ...='cd ..;cd ..'
alias grep='grep --color=auto'
alias ll="ls -lrtF --color"
alias la="ls -alrtF --color"
alias lA="ls -A"
alias l="ls -CF"
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias m='less'
alias md='mkdir'
#alias du='du -ch --max-depth=1'
alias du='du -ch'
alias treeacl='tree -A -C -L 2'
alias gnome-open=xdg-open

alias aptu="sudo apt update && sudo apt dist-upgrade -y"
alias sb="source ~/.bashrc"
alias myip="curl http://ipecho.net/plain; echo"

alias go-vatbook="cd /home/amr/dev/python/django/vatbook/"
alias go-dev="cd /home/amr/dev"
alias a2d="python3 /home/amr/dev/scripts/a2dp.py"

# vim wiki
wikii() {
    gvim -c ":VimwikiIndex"
}

# Git
alias gst='git status -s'
alias gl='git pull -r'
alias gp='git push'
alias gd='git diff | vim'
alias gau='git add --update'
alias gc='git commit -v -m'
alias gca='git commit -v -a -m'
alias gb='git branch'
alias gba='git branch -a'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcot='git checkout -t'
alias gcotb='git checkout --track -b'
alias glog='git log'
alias glogp='git log --pretty=format:"%h %s" --graph'

# Git flow
alias gfs="git flow feature start $1"
alias gfp="git flow feature publish $1"
alias gff="git flow feature finish $1"

# TOMCAT
alias t7w="cd /var/lib/tomcat7$1"
alias t7l="sudo tail -f /var/log/tomcat7/catalina.out"
alias t8w="cd /var/lib/tomcat8$1"
alias t8l="sudo tail -f /var/log/tomcat8/catalina.out"
alias t8s="sudo service tomcat8 $1"

open_idea() {
    idea $1 &> /dev/null &
}

open_sts() {
    sts $1 &> /dev/null &
}


if [ -f ~/dotfiles/bash/aliases-cipal ]; 
then
    source ~/dotfiles/bash/aliases-cipal
fi

if [ -f ~/dotfiles/bash/aliases-manning ]; 
then
    source ~/dotfiles/bash/aliases-manning
fi
