#!/bin/bash

alias v="go-dev && cd manning/vBook/"
alias m="go-dev && cd manning/"
alias cas="go-dev && cd cas/VagrantImages/cas/"
alias mcas="grails run-app -https -Dgrails.env=casDev"
alias mcasd="grails run-app -https -debug-jvm -Dgrails.env=casDev"

alias dv="sudo rm -rf /var/lib/tomcat8/webapps/vbook* && cd /var/lib/tomcat8/webapps/ && sudo cp /home/amr/dev/manning/vBook/build/libs/vbook-0.1.war.original /var/lib/tomcat8/webapps/vbook.war && cd -"

alias s3-ls=s3_ls_summary

alias open_m="open_idea ~/dev/manning/Marketplace"
alias open_mws="open_idea ~/dev/manning/MarketplaceWS"
alias open_madmin="open_idea ~/dev/manning/MarketplaceAdmin"
alias open_maadmin="open_idea ~/dev/manning/ManAdmin"
alias open_v="open_idea ~/dev/manning/vBook"
alias open_i="open_idea ~/dev/manning/ivc"

s3_ls_summary() {
    aws s3 ls --summarize --human-readable --recursive s3://$1
}

if [ -f private-manning-aliases ]; then
    source private-manning-aliases
fi
