#!/bin/bash
#
#GO TO LOCATIONS CIPAL
alias go-csf-parent="go-dev && cd cipal/csf/csf-parent-osgi/"
alias go-styx="cd /home/amr/dev/cipal/styx/trunk/styx-parent-osgi/"
alias go-common-parent="cd /home/amr/dev/cipal/cipalcommon3/cipal-common-parent/"
alias go-felix="cd /home/amr/dev/cipal/felix/"
alias go-et="go-dev && cd cipal/etend_ws/etendering"
alias et="~/dev/cipal/etend_ws/etendering"
alias etw="~/dev/cipal/etend_ws/etendering/etendering-web/"
alias etdb="~/dev/cipal/etend_ws/etendering/etendering-db/"

#FELIX TASKS
alias felix-stop="go-felix && ./felix.sh stop"
alias felix-start="go-felix && ./felix.sh start"
alias felix-status="go-felix && ./felix.sh start"

#SUBVERSION TASKS
alias svn-status="svn status | grep -v .settings | grep -v .classpath | grep -v .project | grep -v target"
alias svn-switch-dev="go-styx && svn switch ^/branches/crab-from-file-dev/styx-parent-osgi"
alias svn-switch-trunk="go-styx && svn switch ^/trunk/styx-parent-osgi"

#RUN MAVEN TASKS
#alias mvn-csf="go-csf-parent && mvn clean install -Dmaven.test.skip=true"
#alias mvn-styx="go-csf-parent && mvn clean install -Dbuild.type=styx"
alias mvn-verify-styx="go-styx && mvn verify -Dbuild.type=styx -Dmaven.integration-test.skip=false"
alias mvn-build-notest="go-styx && mvn clean install -Dmaven.test.skip=true && cd styx-runner/ && mvn clean install pax:provision -Pstandalone"
alias mvn-build="go-styx && mvn clean install && cd styx-runner/ && mvn clean install pax:provision -Pstandalone"
alias mvn-drop="go-styx && cd styx-database && mvn sql:execute liquibase:dropAll && mvn clean install" 
alias mvn-deploy="go-felix && rm -f bundles/* && rm -rf felix/cache/runner/* && mvn-drop && mvn-build-notest && felix-start"
alias mvn-version="mvn versions:set -DnewVersion=$1 -DgenerateBackupPoms=false"
alias mvn-ro="mvn requirejs:optimize -Plocal -f ~/dev/cipal/etend_ws/etendering/etendering-web/"
#alias mvn-common="go-common-parent && mvn clean install -Dmaven.test.skip=true"

#CIPROCURE
alias mysql_test="mysql -u etendering -pgvb3lg13 etendering_test"
alias mysql_speed="/home/amr/dev/scripts/mysql_speedup.sh"

alias deploy-etendering="sudo service tomcat7 stop && sudo rm -rf /var/lib/tomcat7/webapps/etendering* && 
                        cd /home/amr/dev/cipal/etend_ws/etendering/etendering-web && mvn clean install -Dmaven.test.skip=true  && 
                        sudo mv /home/amr/dev/cipal/etend_ws/etendering/etendering-web/target/etendering.war /var/lib/tomcat7/webapps/ && 
                        sudo service tomcat7 start"
alias mysql_reset="mvn clean install -Pclean-db-test -f /home/amr/dev/cipal/etend_ws/etendering/etendering-db/ && mysql -u root -proot etendering_test < /home/amr/dev/cipal/etend_ws/sql/dumps/20160302_genk.sql"


