#!/bin/bash

eval "$(starship init bash)"

[[ -f /etc/bash_completion.d/virtualenvwrapper ]] && source /etc/bash_completion.d/virtualenvwrapper


echo "enabling bash autocompletion if exists"
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

echo "enabling kubectl autocompletion"
#command -v kubectl > /dev/null
if [ $? -eq 0 ]; then
    . ~/Documents/dotfiles/bash/kubectl_completion
fi

echo "enabling git prompt and autocompletion"
# Git branch setup 
source ~/.git-completion.bash
source ~/.git-prompt.sh


echo "enabling eb autocompletion"
# eb autocompletion
if [ -f ~/.local/bin/eb_completion.bash ] ; 
then
    source ~/.local/bin/eb_completion.bash
fi

echo "enabling fuzzy finder"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

echo "enabling nvm and autocompletion"
export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
