#!/bin/bash

eval "$(starship init bash)"

[ -f /etc/bash_completion ] && source /etc/bash_completion
[ -f /etc/bash_completion.d/virtualenvwrapper ] && source /etc/bash_completion.d/virtualenvwrapper
[ -f /usr/local/bin/virtualenvwrapper.sh ]  && source /usr/local/bin/virtualenvwrapper.sh
[ -f ~/.local/bin/virtualenvwrapper.sh ]  && source ~/.local/bin/virtualenvwrapper.sh
[ -f ~/Documents/dotfiles/bash/kubectl_completion ] && source ~/Documents/dotfiles/bash/kubectl_completion
[ -f ~/Documents/dotfiles/git-completion.bash ] && source ~/Documents/dotfiles/git-completion.bash
[ -f ~/Documents/dotfiles/git-prompt.sh ] && source ~/Documents/dotfiles/git-prompt.sh
[ -f ~/.local/bin/eb_completion.bash ] && source ~/.local/bin/eb_completion.bash
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f /home/amr/.sdkman/bin/sdkman-init.sh ] && source ~/.sdkman/bin/sdkman-init.sh
#[ -f /etc/bashrc ] && source /etc/bashrc

alias vim='nvim'
